server:
  port: 8088
  #session过期时间10分钟
  session:
    timeout: 600

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/slxy-select?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://rm-bp18j8d8825oq11o6no.mysql.rds.aliyuncs.com:3306/slxy-select?useUnicode=true&characterEncoding=UTF-8
    username: root
#    password: zql123456@
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      max-active: 100
      min-idle: 20
      max-wait: 60000
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      use-global-data-source-stat: true
      filters: stat,wall,log4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 500

  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/pages/

  #  文件上传大小限制
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启的目录
#      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
#  mail:
#      host: smtp.163.com
#      username: 13108018752@163.com
#      password: zql123456
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true
#              required: true
#      port: 465

mybatis:
  type-aliases-package: com.slxy.www.domain.po
  mapper-locations:
    - classpath:mapper/*Mapper.xml
#
#logging:
#  level:
#    com.slxy.www.dao: trace # 改成你的mapper文件所在包路径